services:
  localstack:
    image: localstack/localstack:latest
    container_name: ai4u-localstack
    restart: unless-stopped
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      - DEBUG=1
      - SERVICES=sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./scripts/localstack:/etc/localstack/init/ready.d
      - localstack_data-ai4u:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 25s
    networks:
      - ai4u-network

volumes:
  localstack_data-ai4u:
    driver: local

networks:
  ai4u-network:
    driver: bridge
    name: ai4u-network
